require 'algoruby/sort/b_f_p_r_t'
require 'algoruby/sort/bucket'
require 'algoruby/sort/counting'
require 'algoruby/sort/heap'
require 'algoruby/sort/insertion'
require 'algoruby/sort/median'
require 'algoruby/sort/quicksort'
require 'algoruby/sort/selection'
